name: Deploy to ECS Fargate

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=$(aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" --query "repositories[0].repositoryUri" --output text)
          docker buildx build --platform linux/arm64 -t $IMAGE_URI:$IMAGE_TAG . --push
          echo "IMAGE_URI=$IMAGE_URI:$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Get current task definition
        id: task-def
        run: |
          aws ecs describe-task-definition \
            --task-definition yallawish2 \
            --query taskDefinition \
            --output json > task-def.json
      - name: Clean task definition
        run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-def.json > cleaned-task-def.json

      - name: Replace image in task definition
        run: |
          NEW_IMAGE="${{ env.IMAGE_URI }}"
          jq '.containerDefinitions[0].image = "'$NEW_IMAGE'"' cleaned-task-def.json > new-task-def.json

      - name: Register new task definition revision
        id: register
        run: |
          REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.revision" \
            --output text)
          echo "REVISION=$REVISION" >> $GITHUB_ENV

      - name: Force ECS New Deployment
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --task-definition yallawish2:${{ env.REVISION }} \
            --force-new-deployment
        env:
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

      - name: Log deployed image and revision
        run: |
          echo "Deploying image: ${{ env.IMAGE_URI }}"
          echo "Deploying revision: ${{ env.REVISION }}"
